using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel()]
public partial class NetworkManagerModel {
    [RealtimeProperty(1, true, true)] private int _numberPlayers = 0;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NetworkManagerModel : RealtimeModel {
    public int numberPlayers {
        get {
            return _numberPlayersProperty.value;
        }
        set {
            if (_numberPlayersProperty.value == value) return;
            _numberPlayersProperty.value = value;
            InvalidateReliableLength();
            FireNumberPlayersDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NetworkManagerModel model, T value);
    public event PropertyChangedHandler<int> numberPlayersDidChange;
    
    public enum PropertyID : uint {
        NumberPlayers = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _numberPlayersProperty;
    
    #endregion
    
    public NetworkManagerModel() : base(null) {
        _numberPlayersProperty = new ReliableProperty<int>(1, _numberPlayers);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _numberPlayersProperty.UnsubscribeCallback();
    }
    
    private void FireNumberPlayersDidChange(int value) {
        try {
            numberPlayersDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _numberPlayersProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _numberPlayersProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.NumberPlayers: {
                    changed = _numberPlayersProperty.Read(stream, context);
                    if (changed) FireNumberPlayersDidChange(numberPlayers);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _numberPlayers = numberPlayers;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
