using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel()]
public partial class NetworkManagerModel {
    [RealtimeProperty(1, true, true)] private int _numberPlayers = 0;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NetworkManagerModel : RealtimeModel {
    public int numberPlayers {
        get {
            return _cache.LookForValueInCache(_numberPlayers, entry => entry.numberPlayersSet, entry => entry.numberPlayers);
        }
        set {
            if (this.numberPlayers == value) return;
            _cache.UpdateLocalCache(entry => { entry.numberPlayersSet = true; entry.numberPlayers = value; return entry; });
            InvalidateReliableLength();
            FireNumberPlayersDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NetworkManagerModel model, T value);
    public event PropertyChangedHandler<int> numberPlayersDidChange;
    
    private struct LocalCacheEntry {
        public bool numberPlayersSet;
        public int numberPlayers;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        NumberPlayers = 1,
    }
    
    public NetworkManagerModel() : this(null) {
    }
    
    public NetworkManagerModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireNumberPlayersDidChange(int value) {
        try {
            numberPlayersDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.NumberPlayers, (uint)_numberPlayers);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.numberPlayersSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.NumberPlayers, (uint)entry.numberPlayers);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.NumberPlayers, (uint)_numberPlayers);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.numberPlayersSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.numberPlayersSet) {
                stream.WriteVarint32((uint)PropertyID.NumberPlayers, (uint)entry.numberPlayers);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.NumberPlayers: {
                    int previousValue = _numberPlayers;
                    _numberPlayers = (int)stream.ReadVarint32();
                    bool numberPlayersExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.numberPlayersSet);
                    if (!numberPlayersExistsInChangeCache && _numberPlayers != previousValue) {
                        FireNumberPlayersDidChange(_numberPlayers);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _numberPlayers = numberPlayers;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
