using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel()]
public partial class NetworkManagerModel {
    [RealtimeProperty(1, true, true)] private bool _nodesInstantiated = false;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NetworkManagerModel : RealtimeModel {
    public bool nodesInstantiated {
        get {
            return _cache.LookForValueInCache(_nodesInstantiated, entry => entry.nodesInstantiatedSet, entry => entry.nodesInstantiated);
        }
        set {
            if (this.nodesInstantiated == value) return;
            _cache.UpdateLocalCache(entry => { entry.nodesInstantiatedSet = true; entry.nodesInstantiated = value; return entry; });
            InvalidateReliableLength();
            FireNodesInstantiatedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NetworkManagerModel model, T value);
    public event PropertyChangedHandler<bool> nodesInstantiatedDidChange;
    
    private struct LocalCacheEntry {
        public bool nodesInstantiatedSet;
        public bool nodesInstantiated;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        NodesInstantiated = 1,
    }
    
    public NetworkManagerModel() : this(null) {
    }
    
    public NetworkManagerModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireNodesInstantiatedDidChange(bool value) {
        try {
            nodesInstantiatedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.NodesInstantiated, _nodesInstantiated ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.nodesInstantiatedSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.NodesInstantiated, entry.nodesInstantiated ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.NodesInstantiated, _nodesInstantiated ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.nodesInstantiatedSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.nodesInstantiatedSet) {
                stream.WriteVarint32((uint)PropertyID.NodesInstantiated, entry.nodesInstantiated ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.NodesInstantiated: {
                    bool previousValue = _nodesInstantiated;
                    _nodesInstantiated = (stream.ReadVarint32() != 0);
                    bool nodesInstantiatedExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.nodesInstantiatedSet);
                    if (!nodesInstantiatedExistsInChangeCache && _nodesInstantiated != previousValue) {
                        FireNodesInstantiatedDidChange(_nodesInstantiated);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _nodesInstantiated = nodesInstantiated;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
