using Normal.Realtime.Serialization;
using UnityEngine;
using Normal.Realtime;

namespace Network {
    [RealtimeModel]
    public partial class NodeModel {
        [RealtimeProperty(1, true, true)] private bool _active;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace Network {
    public partial class NodeModel : RealtimeModel {
        public bool active {
            get {
                return _activeProperty.value;
            }
            set {
                if (_activeProperty.value == value) return;
                _activeProperty.value = value;
                InvalidateReliableLength();
                FireActiveDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(NodeModel model, T value);
        public event PropertyChangedHandler<bool> activeDidChange;
        
        public enum PropertyID : uint {
            Active = 1,
        }
        
        #region Properties
        
        private ReliableProperty<bool> _activeProperty;
        
        #endregion
        
        public NodeModel() : base(null) {
            _activeProperty = new ReliableProperty<bool>(1, _active);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _activeProperty.UnsubscribeCallback();
        }
        
        private void FireActiveDidChange(bool value) {
            try {
                activeDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = 0;
            length += _activeProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var writes = false;
            writes |= _activeProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case (uint) PropertyID.Active: {
                        changed = _activeProperty.Read(stream, context);
                        if (changed) FireActiveDidChange(active);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _active = active;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
