using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NodeModel {
    [RealtimeProperty(1, true, true)] private bool _nodeActivated;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NodeModel : RealtimeModel {
    public bool nodeActivated {
        get {
            return _cache.LookForValueInCache(_nodeActivated, entry => entry.nodeActivatedSet, entry => entry.nodeActivated);
        }
        set {
            if (this.nodeActivated == value) return;
            _cache.UpdateLocalCache(entry => { entry.nodeActivatedSet = true; entry.nodeActivated = value; return entry; });
            InvalidateReliableLength();
            FireNodeActivatedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NodeModel model, T value);
    public event PropertyChangedHandler<bool> nodeActivatedDidChange;
    
    private struct LocalCacheEntry {
        public bool nodeActivatedSet;
        public bool nodeActivated;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        NodeActivated = 1,
    }
    
    public NodeModel() : this(null) {
    }
    
    public NodeModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireNodeActivatedDidChange(bool value) {
        try {
            nodeActivatedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.NodeActivated, _nodeActivated ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.nodeActivatedSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.NodeActivated, entry.nodeActivated ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.NodeActivated, _nodeActivated ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.nodeActivatedSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.nodeActivatedSet) {
                stream.WriteVarint32((uint)PropertyID.NodeActivated, entry.nodeActivated ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.NodeActivated: {
                    bool previousValue = _nodeActivated;
                    _nodeActivated = (stream.ReadVarint32() != 0);
                    bool nodeActivatedExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.nodeActivatedSet);
                    if (!nodeActivatedExistsInChangeCache && _nodeActivated != previousValue) {
                        FireNodeActivatedDidChange(_nodeActivated);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _nodeActivated = nodeActivated;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
