using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TestString {
    [RealtimeProperty(1, true, true)] private string _message;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TestString : RealtimeModel {
    public string message {
        get {
            return _cache.LookForValueInCache(_message, entry => entry.messageSet, entry => entry.message);
        }
        set {
            if (this.message == value) return;
            _cache.UpdateLocalCache(entry => { entry.messageSet = true; entry.message = value; return entry; });
            InvalidateReliableLength();
            FireMessageDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TestString model, T value);
    public event PropertyChangedHandler<string> messageDidChange;
    
    private struct LocalCacheEntry {
        public bool messageSet;
        public string message;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Message = 1,
    }
    
    public TestString() : this(null) {
    }
    
    public TestString(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireMessageDidChange(string value) {
        try {
            messageDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteStringLength((uint)PropertyID.Message, _message);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.messageSet) {
                length += WriteStream.WriteStringLength((uint)PropertyID.Message, entry.message);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteString((uint)PropertyID.Message, _message);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.messageSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.messageSet) {
                stream.WriteString((uint)PropertyID.Message, entry.message);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Message: {
                    string previousValue = _message;
                    _message = stream.ReadString();
                    bool messageExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.messageSet);
                    if (!messageExistsInChangeCache && _message != previousValue) {
                        FireMessageDidChange(_message);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _message = message;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
