using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class DrumSyncModel {
    [RealtimeProperty(1, true, true)] private bool _playAudio;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class DrumSyncModel : RealtimeModel {
    public bool playAudio {
        get {
            return _cache.LookForValueInCache(_playAudio, entry => entry.playAudioSet, entry => entry.playAudio);
        }
        set {
            if (this.playAudio == value) return;
            _cache.UpdateLocalCache(entry => { entry.playAudioSet = true; entry.playAudio = value; return entry; });
            InvalidateReliableLength();
            FirePlayAudioDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(DrumSyncModel model, T value);
    public event PropertyChangedHandler<bool> playAudioDidChange;
    
    private struct LocalCacheEntry {
        public bool playAudioSet;
        public bool playAudio;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        PlayAudio = 1,
    }
    
    public DrumSyncModel() : this(null) {
    }
    
    public DrumSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FirePlayAudioDidChange(bool value) {
        try {
            playAudioDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayAudio, _playAudio ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playAudioSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayAudio, entry.playAudio ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.PlayAudio, _playAudio ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playAudioSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.playAudioSet) {
                stream.WriteVarint32((uint)PropertyID.PlayAudio, entry.playAudio ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.PlayAudio: {
                    bool previousValue = _playAudio;
                    _playAudio = (stream.ReadVarint32() != 0);
                    bool playAudioExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playAudioSet);
                    if (!playAudioExistsInChangeCache && _playAudio != previousValue) {
                        FirePlayAudioDidChange(_playAudio);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _playAudio = playAudio;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
